services:
    _defaults: { autowire: true, autoconfigure: true }

    App\:
        resource: '../src/'
        exclude:
            - '../src/Shared/Infrastructure/Symfony/Kernel.php'

    App\Order\UI\Http\Rest\:
        resource: '../src/Order/UI/Http/Rest/**/*Controller.php'
        tags: [ 'controller.service_arguments' ]

    App\Order\:
        resource: '../src/Order/*'
